[package]
name = "compile"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.38"
env_logger = "0.11.8"
indicatif = "0.17.11"
log = "0.4.27"
rand = "0.9.0"
reqwest = "0.12.15"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.45.0"
